# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mokusou's blog
email: so@moku.fr
description: >- # this means to ignore newlines until "baseurl:"
  技術的な話とか、その他雑多な日記とか
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m0kus0u.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Mokusou4
github_username:  m0kus0u

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  diary:
    output: true
    permalink: /diary/:title/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
